# Site settings
title: Just another blog
email: nhattan2012@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nhattan.github.io" # the base hostname & protocol for your site
github_username:  nhattan
linkedin_username: tannn
name: Nhat Tan

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: Asia/Bangkok
